@Host = http://localhost:3000/products
@ProductId = 62200b52bccdde650aa2ac8a

### Post product
POST {{ Host }}
Content-Type: application/json
Authorization: {{ JWTToken }}

{
  "name": "lorem3 lorem lorem",
  "description": "lorem3 lorem lorem",
  "price": 1,
  "stock": 1900,
  "image": "https://i.imgur.com/U4iGx1j.jpeg",
  "category": {
    "name": "category a",
    "image": "https://i.imgur.com/U4iGx1j.jpeg"
  },
  "brand": "62200b79915d3aa41676de01"
}

### GET Products
GET {{ Host }}

### GET a single product with a given id
GET {{ Host }}/{{ ProductId }}
Authorization: {{ JWTToken }}
